package:
  name: cluster-api-1.9
  version: "1.9.6"
  epoch: 0
  description: Cluster API meta package
  dependencies:
    provides:
      - cluster-api=${{package.full-version}}
  copyright:
    - license: Apache-2.0

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 813e90d8daef60b715764ce4729b40d82f811cc1
      repository: https://github.com/kubernetes-sigs/cluster-api
      tag: v${{package.version}}

subpackages:
  - name: ${{package.name}}-controller
    description: cluster-api core controller
    dependencies:
      provides:
        - cluster-api-controller=${{package.full-version}}
    pipeline:
      - uses: go/build
        with:
          output: manager
          packages: .
          ldflags: |
            -X sigs.k8s.io/cluster-api/version.gitVersion=$(git describe --dirty --tags --always) \
            -X sigs.k8s.io/cluster-api/version.gitCommit=$(git rev-parse HEAD) \
            -X sigs.k8s.io/cluster-api/version.gitTreeState=$(shell git diff --quiet >/dev/null 2>&1 || echo "dirty" || echo "clean") \
            -X sigs.k8s.io/cluster-api/version.buildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

  - name: ${{package.name}}-kubeadm-bootstrap-controller
    description: cluster-api core controller
    dependencies:
      provides:
        - cluster-api-kubeadm-bootstrap-controller=${{package.full-version}}
    pipeline:
      - uses: go/build
        with:
          output: kubeadm-bootstrap-controller
          packages: ./bootstrap/kubeadm
          ldflags: |
            -X sigs.k8s.io/cluster-api/version.gitVersion=$(git describe --dirty --tags --always) \
            -X sigs.k8s.io/cluster-api/version.gitCommit=$(git rev-parse HEAD) \
            -X sigs.k8s.io/cluster-api/version.gitTreeState=$(shell git diff --quiet >/dev/null 2>&1 || echo "dirty" || echo "clean") \
            -X sigs.k8s.io/cluster-api/version.buildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

  - name: ${{package.name}}-kubeadm-controlplane-controller
    description: cluster-api core controller
    dependencies:
      provides:
        - cluster-api-kubeadm-controlplane-controller=${{package.full-version}}
    pipeline:
      - uses: go/build
        with:
          output: kubeadm-controlplane-controller
          packages: ./controlplane/kubeadm
          ldflags: |
            -X sigs.k8s.io/cluster-api/version.gitVersion=$(git describe --dirty --tags --always) \
            -X sigs.k8s.io/cluster-api/version.gitCommit=$(git rev-parse HEAD) \
            -X sigs.k8s.io/cluster-api/version.gitTreeState=$(shell git diff --quiet >/dev/null 2>&1 || echo "dirty" || echo "clean") \
            -X sigs.k8s.io/cluster-api/version.buildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

  - name: ${{package.name}}-clusterctl
    description: cluster-api command line tool
    dependencies:
      provides:
        - clusterctl=${{package.full-version}}
    pipeline:
      - uses: go/build
        with:
          output: clusterctl
          packages: ./cmd/clusterctl
          ldflags: |
            -X sigs.k8s.io/cluster-api/version.gitVersion=$(git describe --dirty --tags --always) \
            -X sigs.k8s.io/cluster-api/version.gitCommit=$(git rev-parse HEAD) \
            -X sigs.k8s.io/cluster-api/version.gitTreeState=$(shell git diff --quiet >/dev/null 2>&1 || echo "dirty" || echo "clean") \
            -X sigs.k8s.io/cluster-api/version.buildDate=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
    test:
      pipeline:
        - runs: |
            clusterctl version | grep -q ${{package.version}}
            clusterctl --help | grep -q "Get started with Cluster API using clusterctl"
            clusterctl config repositories | grep helm

test:
  environment:
    contents:
      packages:
        - kubectl
        - kind
        - kwok
        - busybox
        - kwok
        - kwokctl
        - kubernetes # has a runtime dependency on kubectl
        - etcd
        - ${{package.name}}-controller
        - ${{package.name}}-kubeadm-bootstrap-controller
        - ${{package.name}}-kubeadm-controlplane-controller
        - ${{package.name}}-clusterctl
        - curl
  pipeline:
    - uses: git-checkout
      with:
        expected-commit: 813e90d8daef60b715764ce4729b40d82f811cc1
        repository: https://github.com/kubernetes-sigs/cluster-api
        tag: v${{package.version}}
    - uses: test/kwok/cluster
    - runs: |
        kubectl apply -f config/crd/bases/
    - uses: test/daemon-check-output
      with:
        start: manager --profiler-address=127.0.0.1:8080 --health-addr=127.0.0.1:8081
        expected_output: |
          Starting workers
          Starting webhook server
          Starting EventSource
          All workers finished
    - uses: test/daemon-check-output
      with:
        start: kubeadm-controlplane-controller
        expected_output: |
          Registering webhook
          Conversion webhook enabled
          Starting manager
          problem running manager
    - uses: test/daemon-check-output
      with:
        start: kubeadm-bootstrap-controller
        expected_output: |
          Stopping and waiting for webhooks
          Stopping and waiting for HTTP servers

update:
  enabled: true
  github:
    identifier: kubernetes-sigs/cluster-api
    strip-prefix: v
    tag-filter: v
