package:
  name: cryptopp
  version: "8.9.0"
  epoch: 0
  description: "Seastar is a high-performance, open-source framework for building C++ applications"
  copyright:
    - license: "Apache-2.0"

vars:
  py-version: 3.13
  java-version: 11

environment:
  contents:
    packages:
      - bash
      - bazelisk-default
      - binutils
      - bison
      - boost-dev
      - build-base
      - busybox
      - c-ares-dev
      - ca-certificates-bundle
      - clang-17
      - clang-17-dev
      - cmake
      - coreutils # for GNU install
      - git
      - glibc-locale-en
      - gnutls-dev
      - isl-dev
      - libtool
      - llvm-libcxx-17
      - llvm-libcxx-17-dev
      - llvm-libcxxabi-17
      - llvm-lld-17
      - llvm17
      - llvm17-dev
      - openjdk-${{vars.java-version}}-default-jdk
      - openssl-dev
      - patch
      - py${{vars.py-version}}-absl-py
      - python-${{vars.py-version}}-dev
      - samurai
      - zlib-dev

var-transforms:
  - from: ${{package.version}}
    match: \.
    replace: _
    to: mangled-package-version

pipeline:
  - uses: git-checkout
    with:
      repository: "https://github.com/weidai11/cryptopp.git"
      tag: "CRYPTOPP_${{vars.mangled-package-version}}"
      expected-commit: "843d74c7c97f9e19a615b8ff3c0ca06599ca501b"

  - runs: |
      cp TestScripts/configure.sh .
      ./configure.sh

  - uses: autoconf/make

  - uses: autoconf/make-install

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      ln -s /usr/local/bin/cryptest.exe ${{targets.destdir}}/usr/bin/cryptest

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    description: "Development files for cryptopp"
    dependencies:
      runtime:
        - ${{package.name}}
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  pipeline:
    - name: version check
      runs: |
        /usr/local/bin/cryptest.exe V | grep "${{package.version}}"
    - runs: |
        /usr/local/bin/cryptest.exe h | grep "Test Driver for Crypto++"
    - runs: |
        test -L /usr/bin/cryptest
    - runs: |
        cryptest v | grep "Testing Settings..."

update:
  version-separator: _
  enabled: true
  github:
    identifier: "weidai11/cryptopp"
    use-tag: true
    strip-prefix: "CRYPTOPP_"
