package:
  name: dcmtk
  version: "3.6.9"
  epoch: 0
  description: "DCMTK is a collection of libraries and applications implementing large parts the DICOM standard."
  copyright:
    - license: "MIT"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - doxygen
      - libjpeg-turbo-dev
      - libpng-dev
      - libxml2-dev
      - openssl-dev
      - tiff-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://git.dcmtk.org/dcmtk.git
      tag: DCMTK-${{package.version}}
      expected-commit: ac002900cab167509881e5b837cdef5dcb07cd37
      recurse-submodules: true

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

update:
  enabled: true
  git:
    strip-prefix: DCMTK-
    tag-filter-prefix: DCMTK-3.6

test:
  pipeline:
    - runs: |
        dcm2pnm --help
        dcmdump --help
        dcmpschk --help
        echoscu --help
