---
package:
  name: dcmtk
  version: "3.6.9"  # Adjust to match the Orthanc version discovered
  epoch: 0
  description: "Light-weight, simple and fast XML parser for C++ with XPath support"
  copyright:
    - license: "MIT"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - doxygen
      - openssl-dev
      - libjpeg-turbo-dev
      - libpng-dev
      - tiff-dev
      - libxml2-dev
vars:
  lua-version: "5.4"

# Main build pipeline
pipeline:
  - uses: git-checkout
    with:
      repository: https://git.dcmtk.org/dcmtk.git
      tag: DCMTK-${{package.version}}
      expected-commit: ac002900cab167509881e5b837cdef5dcb07cd37
      recurse-submodules: true  

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install