package:
  name: gdcm
  version: "3.1.0"
  epoch: 0
  description: "Grassroots DICOM Gdcm, Cross-platform DICOM implementation library for C++"
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - patch

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/malaterre/GDCM
      tag: v${{package.version}}
      expected-commit: 917a96c8f4d63f2a30ac3a52f31d90127c2d6607

  - uses: patch
    with:
      patches: numeric-limits.patch

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

test:
  pipeline:
    - name: Test headers and pkg-config
      runs: |
        # Test that headers are installed
        stat /usr/include/gdcm-3.1/gdcm*.h
        # Test that cmake config is installed
        stat /usr/lib/gdcm-3.1/GDCMConfig.cmake
        # Test that libraries are installed
        stat /usr/lib/libgdcm*.a

update:
  enabled: true
  git:
    strip-prefix: v
    tag-filter-contains: v
