package:
  name: grafana-rollout-operator
  version: "0.31.0"
  epoch: 0 # CVE-2025-47910
  description: Kubernetes Rollout Operator
  copyright:
    - license: Apache-2.0
  dependencies:
    # REMOVE_POST_USRMERGE - https://github.com/orgs/wolfi-dev/discussions/40270
    provides:
      - ${{package.name}}-compat=${{package.full-version}}
    runtime:
      - merged-bin
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/grafana/rollout-operator
      tag: v${{package.version}}
      expected-commit: 4dbcfff9dac6a290eaf9c4e1396470de7a858919

  - uses: go/build
    with:
      packages: ./cmd/rollout-operator
      output: rollout-operator

test:
  pipeline:
    - runs: |
        rollout-operator --help

update:
  enabled: true
  github:
    identifier: grafana/rollout-operator
    strip-prefix: v
