package:
  name: ohif-viewer
  version: "3.10.2"
  epoch: 0
  description: "OHIF zero-footprint DICOM viewer and oncology specific Lesion Tracker, plus shared extension packages"
  copyright:
    - license: "MIT"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - nodejs
      - npm
      - python3
      - yarn

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/OHIF/Viewers
      tag: v${{package.version}}
      expected-commit: 9a4a40468fc61e8c4818ea57905239bdff47f634

  # Minimal build req for orthanc-ohif web assests
  - name: Build OHIF viewer
    runs: |
      yarn install --frozen-lockfile --ignore-scripts
      yarn build
      mkdir -p "${{targets.destdir}}/usr/share/ohif-viewer/dist"
      cp -r platform/app/dist/* "${{targets.destdir}}/usr/share/ohif-viewer/dist"

test:
  pipeline:
    - name: Test built assets
      runs: |
        stat /usr/share/ohif-viewer/dist

update:
  enabled: true
  ignore-regex-patterns:
    - '.*beta.*'
  git:
    strip-prefix: v
    tag-filter-contains: v
