package:
  name: orthanc-ohif
  version: 1.6
  epoch: 0
  description: OHIF plugin for Orthanc DICOM server - modern DICOM web viewer
  copyright:
    - license: AGPL-3.0-or-later
  dependencies:
    runtime:
      - boost-filesystem
      - boost-iostreams
      - boost-thread
      - jsoncpp
      - libuuid
      - zlib

environment:
  contents:
    packages:
      - boost-dev
      - build-base
      - e2fsprogs-dev
      - gtest-dev
      - jsoncpp-dev
      - libuuid
      - nodejs
      - npm
      - patch
      - util-linux-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://orthanc.uclouvain.be/downloads/sources/orthanc-ohif/OrthancOHIF-${{package.version}}.tar.gz
      expected-sha256: dc8b64307d41105f1bb112f2ee499e404650d6dabf3363a3b916a4d8642891d2

  - name: Build web assets
    runs: |
      # The OHIF viewer assets need to be built
      if [ -d "Resources/Orthanc/WebApplication" ]; then
        cd Resources/Orthanc/WebApplication
        if [ -f "package.json" ]; then
          npm install
          npm run build
        fi
        cd -
      fi

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DALLOW_DOWNLOADS=ON \
        -DUSE_SYSTEM_ORTHANC_SDK=OFF \
        -DUSE_SYSTEM_JSONCPP=ON \
        -DUSE_SYSTEM_BOOST=ON \
        -DBUILD_TESTING=ON

  - uses: cmake/build

  - uses: cmake/install

  - runs: |
      # Install the OHIF plugin
      mkdir -p ${{targets.destdir}}/usr/lib/orthanc/plugins/
      if [ -f /usr/lib/libOrthancOHIF.so ]; then
        cp /usr/lib/libOrthancOHIF.so ${{targets.destdir}}/usr/lib/orthanc/plugins/
      fi

test:
  pipeline:
    - runs: |
        # Test that the plugin library exists and has correct format
        test -f /usr/lib/orthanc/plugins/libOrthancOHIF.so
        ldd /usr/lib/orthanc/plugins/libOrthancOHIF.so
