package:
  name: orthanc
  version: "1.12.7"
  epoch: 0
  description: "Orthanc - a lightweight DICOM server for medical imaging"
  copyright:
    - license: "AGPL-3.0-or-later"

environment:
  contents:
    packages:
      - boost-dev
      - build-base
      - busybox
      - curl
      - curl-dev
      - dcmtk
      - doxygen
      - gtest-dev
      - jsoncpp-dev
      - libjpeg-turbo-dev
      - libpng-dev
      - lua5.4-dev
      - ninja
      - openssl-dev
      - patch
      - protobuf-dev
      - pugixml
      - python3
      - sqlite-dev

vars:
  lua-version: "5.4"

pipeline:
  - uses: fetch
    with:
      uri: https://orthanc.uclouvain.be/downloads/sources/orthanc/Orthanc-${{package.version}}.tar.gz
      expected-sha256: f4349971c9e12f74599ba036c37ce7fe7fe8078b08dddbb83e08cf7b13e53adb

  - uses: cmake/configure
    with:
      opts: |
        -DPUGIXML_DIR=/usr/lib/cmake/pugixml \
        -DSTANDALONE_BUILD=ON \
        -DALLOW_DOWNLOADS=ON \
        -DUSE_BUNDLED_JSONCPP=On \
        -DUSE_SYSTEM_CIVETWEB=OFF \
        -DUSE_GOOGLE_TEST_DEBIAN_PACKAGE=OFF \
        -DDCMTK_LIBRARIES=dcmjpls \
        -DLUA_LIBRARIES=/usr/lib/lua5.4/liblua.so \
        -DCMAKE_BUILD_TYPE=Release \
        -DENABLE_PUGIXML=OFF \
        -DUSE_SYSTEM_DCMTK=OFF \
        -DUSE_SYSTEM_OPENSSL=OFF \
        -DUSE_SYSTEM_CURL=ON \
        -DUNIT_TESTS_WITH_HTTP_CONNEXIONS=OFF \
        -S ./OrthancServer/

  - uses: cmake/build

  - uses: cmake/install

  - runs: |
      mv ${{targets.destdir}}/usr/sbin/* ${{targets.destdir}}/usr/bin/
      rmdir ${{targets.destdir}}/usr/sbin/

  - uses: strip

subpackages:
  - name: ${{package.name}}-postgresql
    environment:
    contents:
      packages:
        - patch
        - openssl-dev
        - gtest-dev
        - protobuf-dev
        - jsoncpp-dev
        - libuuid
        - e2fsprogs
        - python3
        - boost-dev
        - postgresql
        - postgresql-dev
    pipeline:
      - uses: fetch
        with:
          uri: https://orthanc.uclouvain.be/downloads/sources/orthanc-postgresql/OrthancPostgreSQL-7.2.tar.gz
          expected-sha256: de20ddff1e6cdeeb0ea0de626f7eec27638e94e775595faba460613c00830841
      - uses: cmake/configure
        with:
          opts: |
            -DALLOW_DOWNLOADS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DUSE_SYSTEM_ORTHANC_SDK=OFF \
            -DPostgreSQL_INCLUDE_DIR=/usr/include \
            -S ./PostgreSQL/
      - uses: cmake/build
      - uses: cmake/install

  - name: ${{package.name}}-dicomweb
    environment:
    contents:
      packages:
        - patch
        - pugixml
        - jsoncpp-dev
        - gtest-dev
        - libuuid
        - e2fsprogs
        - python3
        - zlib-dev
        - util-linux-dev
        - boost-dev
    pipeline:
      - uses: fetch
        with:
          uri: https://orthanc.uclouvain.be/downloads/sources/orthanc-dicomweb/OrthancDicomWeb-1.20.tar.gz
          expected-sha256: 1e8adcaffc97b891bb7030987c47ccd4c4d952ac43217c9813164e963bd3a9ac
      - uses: cmake/configure
        with:
          opts: |
            -DALLOW_DOWNLOADS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DUSE_SYSTEM_ORTHANC_SDK=OFF \
            -S ./
      - uses: cmake/build
      - uses: cmake/install

  - name: ${{package.name}}-Explorer2
    environment:
    contents:
      packages:
        - mercurial
        - patch
        - jsoncpp-dev
        - libuuid
        - e2fsprogs
        - util-linux-dev
        - boost-dev
    pipeline:
      - uses: fetch
        with:
          uri: https://orthanc.uclouvain.be/downloads/sources/orthanc-explorer-2/OrthancExplorer2-1.8.3.tar.gz
          expected-sha256: ec7894700275e5150f7125e792f3cfea9e92496d36433bac109a68f60979ded5
      - uses: cmake/configure
        with:
          opts: |
            -DALLOW_DOWNLOADS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DUSE_SYSTEM_ORTHANC_SDK=OFF \
            -S ./
      - uses: cmake/build
      - uses: cmake/install

  - name: ${{package.name}}-ohif
    environment:
    contents:
      packages:
        - patch
        - jsoncpp-dev
        - libuuid
        - e2fsprogs
        - util-linux-dev
        - boost-dev
        - zlib-dev
    pipeline:
      - uses: fetch
        with:
          uri: https://orthanc.uclouvain.be/downloads/sources/orthanc-ohif/OrthancOHIF-1.6.tar.gz
          expected-sha256: dc8b64307d41105f1bb112f2ee499e404650d6dabf3363a3b916a4d8642891d2
      - uses: cmake/configure
        with:
          opts: |
            -DALLOW_DOWNLOADS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DUSE_SYSTEM_ORTHANC_SDK=OFF \
            -S ./
      - uses: cmake/build
      - uses: cmake/install

  - name: ${{package.name}}-python
    environment:
    contents:
      packages:
        - python-3.12
        - python-3.12-dev
        - patch
        - jsoncpp-dev
        - libuuid
        - e2fsprogs
        - util-linux-dev
        - boost-dev
    pipeline:
      - uses: fetch
        with:
          uri: https://orthanc.uclouvain.be/downloads/sources/orthanc-python/OrthancPython-5.0.tar.gz
          expected-sha256: a0df1ba5082b0dab558b70ec9447c5954cb7d9b568bcb9e4a7a4d1b86fb103f6
      - uses: cmake/configure
        with:
          opts: |
            -DALLOW_DOWNLOADS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DUSE_SYSTEM_ORTHANC_SDK=OFF \
            -DPYTHON_VERSION=3.12 \
            -S ./
      - uses: cmake/build
      - uses: cmake/install

  - name: ${{package.name}}-gdcm
    environment:
    contents:
      packages:
        - patch
    pipeline:
      - uses: fetch
        with:
          uri: https://orthanc.uclouvain.be/downloads/sources/orthanc-gdcm/OrthancGdcm-1.8.tar.gz
          expected-sha256: c72a169ab7e03fbae2634c1eb4fbc26d801e716026b4561c3a414e366f7759c1
      - uses: cmake/configure
        with:
          opts: |
            -DALLOW_DOWNLOADS=ON \
            -DCMAKE_BUILD_TYPE=Release \
            -DSTATIC_BUILD=ON \
            -S ./
      - uses: cmake/build
      - uses: cmake/install

test:
  pipeline:
    - uses: test/tw/ldd-check

update:
  enabled: true
  release-monitor:
    identifier: 18629
