package:
  name: orthanc-gdcm
  version: 1.8
  epoch: 0
  description: GDCM plugin for Orthanc DICOM server - advanced DICOM image decoding
  copyright:
    - license: AGPL-3.0-or-later
  dependencies:
    runtime:
      - boost-filesystem
      - boost-iostreams
      - boost-thread
      - jsoncpp
      - libuuid

environment:
  contents:
    packages:
      - boost-dev
      - build-base
      - busybox
      - e2fsprogs-dev
      - gtest-dev
      - jsoncpp-dev
      - libuuid
      - patch
      - python3
      - util-linux-dev

pipeline:
  - uses: fetch
    with:
      uri: https://orthanc.uclouvain.be/downloads/sources/orthanc-gdcm/OrthancGdcm-${{package.version}}.tar.gz
      expected-sha256: c72a169ab7e03fbae2634c1eb4fbc26d801e716026b4561c3a414e366f7759c1

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DALLOW_DOWNLOADS=ON \
        -DSTATIC_BUILD=ON \
        -DUSE_SYSTEM_ORTHANC_SDK=OFF \
        -DUSE_SYSTEM_JSONCPP=ON \
        -DUSE_SYSTEM_BOOST=ON \
        -DBUILD_TESTING=ON

  - uses: cmake/build

  - uses: cmake/install

  - runs: |
      # Install the GDCM plugin
      mkdir -p ${{targets.destdir}}/usr/lib/orthanc/plugins/
      if [ -f /usr/lib/libOrthancGdcm.so ]; then
        cp /usr/lib/libOrthancGdcm.so ${{targets.destdir}}/usr/lib/orthanc/plugins/
      fi

  - uses: strip

test:
  pipeline:
    - runs: |
        # Test that the plugin library exists and has correct format
        test -f /usr/lib/orthanc/plugins/libOrthancGdcm.so
        ldd /usr/lib/orthanc/plugins/libOrthancGdcm.so
