package:
  name: orthanc-python
  version: 5.0
  epoch: 0
  description: Python plugin for Orthanc DICOM server
  copyright:
    - license: AGPL-3.0-or-later
  dependencies:
    runtime:
      - orthanc

environment:
  contents:
    packages:
      - boost-dev
      - build-base
      - e2fsprogs-dev
      - gtest-dev
      - jsoncpp-dev
      - libuuid
      - patch
      - python3
      - python3-dev
      - util-linux-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://orthanc.uclouvain.be/downloads/sources/orthanc-python/OrthancPython-${{package.version}}.tar.gz
      expected-sha256: a0df1ba5082b0dab558b70ec9447c5954cb7d9b568bcb9e4a7a4d1b86fb103f6

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DALLOW_DOWNLOADS=ON \
        -DUSE_SYSTEM_ORTHANC_SDK=OFF \
        -DUSE_SYSTEM_JSONCPP=ON \
        -DUSE_SYSTEM_BOOST=ON \
        -DPYTHON_VERSION=3.12 \
        -DBUILD_TESTING=ON

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

test:
  pipeline:
    - runs: |
        # Test that the plugin library exists and has correct format
        test -f /usr/lib/orthanc/plugins/libOrthancPython.so
        ldd /usr/lib/orthanc/plugins/libOrthancPython.so
        # Test Python can be imported
        python3 -c "import sys; print(sys.version)"

update:
  enabled: true
  release-monitor:
    identifier: 378477
