package:
  name: orthanc-postgresql
  version: 7.2
  epoch: 0
  description: PostgreSQL plugin for Orthanc DICOM server
  copyright:
    - license: AGPL-3.0-or-later
  dependencies:
    runtime:
      - boost-filesystem
      - boost-iostreams
      - boost-thread
      - jsoncpp
      - libuuid
      - postgresql-client
      - zlib

environment:
  contents:
    packages:
      - boost-dev
      - build-base
      - e2fsprogs-dev
      - gtest-dev
      - jsoncpp-dev
      - libuuid
      - patch
      - postgresql-dev
      - python3
      - util-linux-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://orthanc.uclouvain.be/downloads/sources/orthanc-postgresql/OrthancPostgreSQL-${{package.version}}.tar.gz
      expected-sha256: de20ddff1e6cdeeb0ea0de626f7eec27638e94e775595faba460613c00830841

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DALLOW_DOWNLOADS=ON \
        -DUSE_SYSTEM_ORTHANC_SDK=OFF \
        -DUSE_SYSTEM_JSONCPP=ON \
        -DUSE_SYSTEM_BOOST=ON \
        -DPostgreSQL_INCLUDE_DIR=/usr/include/postgresql \
        -DBUILD_TESTING=ON \
        -S ./PostgreSQL/

  - uses: cmake/build

  - uses: cmake/install

  - runs: |
      # Install both index and storage plugins
      mkdir -p ${{targets.destdir}}/usr/lib/orthanc/plugins/
      if [ -f /usr/lib/libOrthancPostgreSQLIndex.so ]; then
        cp /usr/lib/libOrthancPostgreSQLIndex.so ${{targets.destdir}}/usr/lib/orthanc/plugins/
      fi
      if [ -f /usr/lib/libOrthancPostgreSQLStorage.so ]; then
        cp /usr/lib/libOrthancPostgreSQLStorage.so ${{targets.destdir}}/usr/lib/orthanc/plugins/
      fi

test:
  pipeline:
    - runs: |
        # Test that the plugin libraries exist and have correct format
        test -f /usr/lib/orthanc/plugins/libOrthancPostgreSQLIndex.so
        test -f /usr/lib/orthanc/plugins/libOrthancPostgreSQLStorage.so
        ldd /usr/lib/orthanc/plugins/libOrthancPostgreSQLIndex.so
        ldd /usr/lib/orthanc/plugins/libOrthancPostgreSQLStorage.so
