package:
  name: orthanc-dicomweb
  version: 1.20
  epoch: 0
  description: DICOMweb plugin for Orthanc DICOM server - RESTful DICOM services
  copyright:
    - license: AGPL-3.0-or-later
  dependencies:
    runtime:
      - boost-filesystem
      - boost-iostreams
      - boost-thread
      - jsoncpp
      - libuuid
      - pugixml
      - zlib

environment:
  contents:
    packages:
      - boost-dev
      - build-base
      - e2fsprogs-dev
      - gtest-dev
      - jsoncpp-dev
      - libuuid
      - patch
      - pugixml
      - python3
      - util-linux-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://orthanc.uclouvain.be/downloads/sources/orthanc-dicomweb/OrthancDicomWeb-${{package.version}}.tar.gz
      expected-sha256: 1e8adcaffc97b891bb7030987c47ccd4c4d952ac43217c9813164e963bd3a9ac

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DALLOW_DOWNLOADS=ON \
        -DUSE_SYSTEM_ORTHANC_SDK=OFF \
        -DUSE_SYSTEM_JSONCPP=ON \
        -DUSE_SYSTEM_PUGIXML=ON \
        -DUSE_SYSTEM_BOOST=ON \
        -DBUILD_TESTING=ON \
        -DUNIT_TESTS_WITH_HTTP_CONNEXIONS=OFF

  - uses: cmake/build

  - uses: cmake/install

  - runs: |
      # Install the DICOMweb plugin
      mkdir -p ${{targets.destdir}}/usr/lib/orthanc/plugins/
      if [ -f /usr/lib/libOrthancDicomWeb.so ]; then
        cp /usr/lib/libOrthancDicomWeb.so ${{targets.destdir}}/usr/lib/orthanc/plugins/
      fi

  - uses: strip

test:
  pipeline:
    - runs: |
        # Test that the plugin library exists and has correct format
        test -f /usr/lib/orthanc/plugins/libOrthancDicomWeb.so
        ldd /usr/lib/orthanc/plugins/libOrthancDicomWeb.so
