package:
  name: orthanc
  version: "1.12.7"
  epoch: 0
  description: "Orthanc - a lightweight DICOM server for medical imaging"
  copyright:
    - license: "AGPL-3.0-or-later"

environment:
  contents:
    packages:
      - boost-dev
      - build-base
      - busybox
      - curl-dev
      - dcmtk-dev
      - doxygen
      - gtest-dev
      - jsoncpp-dev
      - libjpeg-turbo-dev
      - libpng-dev
      - lua${{vars.lua-version}}-dev
      - ninja
      - openssl-dev
      - patch
      - protobuf-dev
      - pugixml-dev
      - python${{vars.py-version}}
      - sqlite-dev

vars:
  lua-version: "5.4"
  py-version: "3.13"

pipeline:
  - uses: fetch
    with:
      uri: https://orthanc.uclouvain.be/downloads/sources/orthanc/Orthanc-${{package.version}}.tar.gz
      expected-sha256: f4349971c9e12f74599ba036c37ce7fe7fe8078b08dddbb83e08cf7b13e53adb

  - uses: cmake/configure
    with:
      opts: |
        -DPUGIXML_DIR=/usr/lib/cmake/pugixml \
        -DSTANDALONE_BUILD=ON \
        -DALLOW_DOWNLOADS=ON \
        -DUSE_BUNDLED_JSONCPP=On \
        -DUSE_SYSTEM_CIVETWEB=OFF \
        -DUSE_GOOGLE_TEST_DEBIAN_PACKAGE=OFF \
        -DDCMTK_LIBRARIES=dcmjpls \
        -DLUA_LIBRARIES=/usr/lib/lua${{vars.lua-version}}/liblua.so \
        -DCMAKE_BUILD_TYPE=Release \
        -DENABLE_PUGIXML=ON \
        -DUSE_SYSTEM_DCMTK=ON \
        -DUSE_SYSTEM_OPENSSL=ON \
        -DUSE_SYSTEM_CURL=ON \
        -DUNIT_TESTS_WITH_HTTP_CONNEXIONS=OFF \
        -S ./OrthancServer/

  - uses: cmake/build

  - uses: cmake/install

  - runs: |
      mv ${{targets.destdir}}/usr/sbin/* ${{targets.destdir}}/usr/bin/
      rmdir ${{targets.destdir}}/usr/sbin/

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    description: Development files for Orthanc
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - orthanc
    test:
      pipeline:
        - uses: test/tw/ldd-check

  - name: ${{package.name}}-compat
    description: Symlinks for Orthanc
    pipeline:
      - runs: |
          # Upstream image installs it to /usr/local/bin
          mkdir -p ${{targets.subpkgdir}}/usr/local/bin
          ln -sf /usr/bin/Orthanc ${{targets.subpkgdir}}/usr/local/bin/Orthanc

          # Create timezone symlink to fix the /etc/localtime requirement
          mkdir -p ${{targets.subpkgdir}}/etc
          ln -sf /usr/share/zoneinfo/UTC ${{targets.subpkgdir}}/etc/localtime

          # Compatibility symlinks for plugins
          mkdir -p ${{targets.subpkgdir}}/usr/share/orthanc/plugins-available/
          ln -sf /usr/share/orthanc/plugins/libModalityWorklists.so ${{targets.subpkgdir}}/usr/share/orthanc/plugins-available/
          ln -sf /usr/share/orthanc/plugins/libServeFolders.so ${{targets.subpkgdir}}/usr/share/orthanc/plugins-available/
          ln -sf /usr/share/orthanc/plugins/libHousekeeper.so ${{targets.subpkgdir}}/usr/share/orthanc/plugins-available/
          ln -sf /usr/share/orthanc/plugins/libConnectivityChecks.so ${{targets.subpkgdir}}/usr/share/orthanc/plugins-available/
          ln -sf /usr/share/orthanc/plugins/libMultitenantDicom.so ${{targets.subpkgdir}}/usr/share/orthanc/plugins-available/
    dependencies:
      runtime:
        - tzdata
        - ${{package.name}}
    test:
      pipeline:
        - runs: |
            readlink -f /usr/local/bin/Orthanc | grep "/usr/bin/Orthanc"
            readlink -f /etc/localtime | grep "/usr/share/zoneinfo/UTC"
            readlink -f /usr/share/orthanc/plugins-available/libModalityWorklists.so | grep "/usr/share/orthanc/plugins/libModalityWorklists.so"
            readlink -f /usr/share/orthanc/plugins-available/libServeFolders.so | grep "/usr/share/orthanc/plugins/libServeFolders.so"
            readlink -f /usr/share/orthanc/plugins-available/libHousekeeper.so | grep "/usr/share/orthanc/plugins/libHousekeeper.so"
            readlink -f /usr/share/orthanc/plugins-available/libConnectivityChecks.so | grep "/usr/share/orthanc/plugins/libConnectivityChecks.so"
            readlink -f /usr/share/orthanc/plugins-available/libMultitenantDicom.so | grep "/usr/share/orthanc/plugins/libMultitenantDicom.so"

test:
  environment:
    contents:
      packages:
        - ${{package.name}}-compat
        - curl
  pipeline:
    - name: Test installation
      runs: |
        /usr/bin/Orthanc --version
        /usr/bin/Orthanc --help
    - name: Test server startup
      runs: |
        mkdir -p /tmp/orthanc-test

        cat > /tmp/orthanc-test.json << 'EOF'
        {
          "Name": "TestOrthanc",
          "HttpPort": 18042,
          "DicomPort": 14242,
          "RemoteAccessAllowed": true,
          "AuthenticationEnabled": false,
          "Plugins": [],
          "StorageDirectory": "/tmp/orthanc-test",
          "IndexDirectory": "/tmp/orthanc-test"
        }
        EOF
    - uses: test/daemon-check-output
      with:
        start: /usr/bin/Orthanc /tmp/orthanc-test.json --no-jobs
        timeout: 30
        expected_output: |
          Orthanc has started
    - name: Test REST API
      runs: |
        mkdir -p /tmp/orthanc-api-test

        cat > /tmp/orthanc-api.json << 'EOF'
        {
          "Name": "APITestOrthanc",
          "HttpPort": 18043,
          "DicomPort": 14243,
          "RemoteAccessAllowed": true,
          "AuthenticationEnabled": false,
          "Plugins": [],
          "StorageDirectory": "/tmp/orthanc-api-test",
          "IndexDirectory": "/tmp/orthanc-api-test"
        }
        EOF
    - uses: test/daemon-check-output
      with:
        start: /usr/bin/Orthanc /tmp/orthanc-api.json --no-jobs
        timeout: 30
        expected_output: |
          Orthanc has started
        post: |
          curl -s http://localhost:18043/system | grep -q '"Name" : "APITestOrthanc"' && echo "REST API test passed"
    - name: Test DICOM protocol
      runs: |
        mkdir -p /tmp/orthanc-dicom-test

        cat > /tmp/orthanc-dicom.json << 'EOF'
        {
          "Name": "DICOMTestOrthanc",
          "HttpPort": 18044,
          "DicomPort": 14244,
          "RemoteAccessAllowed": true,
          "AuthenticationEnabled": false,
          "DicomAet": "ORTHANC_TEST",
          "DicomCheckCalledAet": false,
          "Plugins": [],
          "StorageDirectory": "/tmp/orthanc-dicom-test",
          "IndexDirectory": "/tmp/orthanc-dicom-test"
        }
        EOF
    - uses: test/daemon-check-output
      with:
        start: /usr/bin/Orthanc /tmp/orthanc-dicom.json --no-jobs
        timeout: 30
        expected_output: |
          DICOM server listening with AET ORTHANC_TEST on port: 14244

update:
  enabled: true
  release-monitor:
    identifier: 18629
