package:
  name: orthanc-postgresql
  version: 7.2
  epoch: 0
  description: PostgreSQL plugin for Orthanc DICOM server
  copyright:
    - license: AGPL-3.0-or-later
  dependencies:
    runtime:
      - orthanc
      - orthanc-compat
      - postgresql-client

environment:
  contents:
    packages:
      - boost-dev
      - build-base
      - busybox
      - e2fsprogs-dev
      - gtest-dev
      - jsoncpp-dev
      - libuuid
      - patch
      - postgresql-dev
      - protobuf-dev
      - python-${{vars.py-version}}
      - util-linux-dev
      - zlib-dev

vars:
  py-version: "3.13"

pipeline:
  - uses: fetch
    with:
      uri: https://orthanc.uclouvain.be/downloads/sources/orthanc-postgresql/OrthancPostgreSQL-${{package.version}}.tar.gz
      expected-sha256: de20ddff1e6cdeeb0ea0de626f7eec27638e94e775595faba460613c00830841

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DALLOW_DOWNLOADS=ON \
        -DUSE_SYSTEM_ORTHANC_SDK=OFF \
        -DUSE_SYSTEM_JSONCPP=ON \
        -DUSE_SYSTEM_BOOST=ON \
        -DPostgreSQL_INCLUDE_DIR=/usr/include/postgresql \
        -S ./PostgreSQL/

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    description: Compatibility symlinks for Orthanc PostgreSQL plugin
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/share/orthanc/plugins-available/
          ln -sf /usr/share/orthanc/plugins/libOrthancPostgreSQLIndex.so ${{targets.subpkgdir}}/usr/share/orthanc/plugins-available/
          ln -sf /usr/share/orthanc/plugins/libOrthancPostgreSQLStorage.so ${{targets.subpkgdir}}/usr/share/orthanc/plugins-available/
    dependencies:
      runtime:
        - ${{package.name}}
    test:
      pipeline:
        - runs: |
            readlink -f /usr/share/orthanc/plugins-available/libOrthancPostgreSQLIndex.so | grep "/usr/share/orthanc/plugins/libOrthancPostgreSQLIndex.so"
            readlink -f /usr/share/orthanc/plugins-available/libOrthancPostgreSQLStorage.so | grep "/usr/share/orthanc/plugins/libOrthancPostgreSQLStorage.so"

test:
  environment:
    contents:
      packages:
        - curl
  pipeline:
    - name: Test plugin installation
      runs: |
        stat /usr/share/orthanc/plugins/libOrthancPostgreSQLIndex.so
        stat /usr/share/orthanc/plugins/libOrthancPostgreSQLStorage.so
    - runs: |
        mkdir -p /tmp/orthanc-postgresql-test

        cat > /tmp/orthanc-postgresql.json << 'EOF'
        {
          "Name": "PostgreSQLTest",
          "HttpPort": 18054,
          "DicomPort": 14254,
          "RemoteAccessAllowed": true,
          "AuthenticationEnabled": false,
          "Plugins": [
            "/usr/share/orthanc/plugins/libOrthancPostgreSQLIndex.so",
            "/usr/share/orthanc/plugins/libOrthancPostgreSQLStorage.so"
          ],
          "PostgreSQL": {
            "EnableIndex": true,
            "EnableStorage": false,
            "Host": "localhost",
            "Port": 5432,
            "Database": "orthanc_test",
            "Username": "orthanc",
            "Password": "orthanc",
            "Lock": true,
            "EnableSsl": false,
            "MaximumConnectionRetries": 10,
            "ConnectionRetryInterval": 5,
            "IndexConnectionsCount": 50,
            "TransactionMode": "ReadCommitted",
            "EnableVerboseLogs": false,
            "HousekeepingInterval": 1,
            "AllowInconsistentChildCounts": false
          },
          "StorageDirectory": "/tmp/orthanc-postgresql-test",
          "IndexDirectory": "/tmp/orthanc-postgresql-test"
        }
        EOF
    - name: Test Orthanc startup with PostgreSQL (expected to fail)
      runs: |
        # Test that Orthanc can parse PostgreSQL configuration and attempt to start
        # This will fail due to no PostgreSQL server, but should show proper plugin loading
        /usr/bin/Orthanc /tmp/orthanc-postgresql.json --no-jobs > /tmp/orthanc-output.log 2>&1 || true

        # Check for plugin loading success
        if grep -q "postgresql-index\|PostgreSQL.*index" /tmp/orthanc-output.log; then
          echo "PostgreSQL Index plugin loaded successfully"
        else
          echo "PostgreSQL Index plugin loading not detected"
        fi

        if grep -q "postgresql-storage\|PostgreSQL.*storage" /tmp/orthanc-output.log; then
          echo "PostgreSQL Storage plugin loaded successfully"
        else
          echo "PostgreSQL Storage plugin not used (expected - EnableStorage=false)"
        fi

        # Check for expected database connection error
        if grep -q "connection.*refused\|could not connect\|Connection refused\|database.*error\|PostgreSQL.*error" /tmp/orthanc-output.log; then
          echo "Expected database connection error occurred"
        else
          echo "No obvious database connection error found"
        fi

update:
  enabled: true
  release-monitor:
    identifier: 378487
