package:
  name: orthanc-builder
  version: "25.5.1"
  epoch: 0
  description: "Repo used to build orthancteam/orthanc docker images, windows installers and OSX packages"
  copyright:
    - license: "AGPL-3.0-or-later"

environment:
  contents:
    packages:
      - build-base
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/orthanc-server/orthanc-builder
      tag: ${{package.version}}
      expected-commit: 080528e2325b73b077376014b8f9eb61615cd22d

  - runs: |
      mkdir ${{targets.contextdir}}/startup
      mkdir ${{targets.contextdir}}/lua-scripts
      mkdir ${{targets.contextdir}}/probes
      cp ./docker/orthanc/docker-entrypoint.sh ${{targets.contextdir}}/
      cp ./docker/orthanc/*.json ${{targets.contextdir}}/startup/
      cp ./docker/orthanc/generateConfiguration.py ${{targets.contextdir}}/startup/
      cp ./docker/orthanc/helpers.py  ${{targets.contextdir}}/startup/
      cp ./docker/orthanc/configurator.py ${{targets.contextdir}}/startup/
      cp ./docker/orthanc/docker-entrypoint.sh ${{targets.contextdir}}/startup/
      cp ./docker/orthanc/*.lua ${{targets.contextdir}}/lua-scripts
      cp ./docker/orthanc/test-aliveness.py ${{targets.contextdir}}/probes/

  - uses: strip

vars:
  py-version: "3.13"

test:
  environment:
    contents:
      packages:
        - bash
        - orthanc
        - orthanc-compat
        - python-${{vars.py-version}}
        - py${{vars.py-version}}-envsubst
        - orthanc-dicomweb
        - orthanc-dicomweb-compat
        - orthanc-python
        - orthanc-python-compat
        - orthanc-ohif
        - orthanc-ohif-compat
        - orthanc-gdcm
        - orthanc-gdcm-compat
        - orthanc-postgresql
        - orthanc-postgresql-compat
        - orthanc-explorer2
        - orthanc-explorer2-compat
  pipeline:
    - uses: test/daemon-check-output
      with:
        start: /docker-entrypoint.sh /startup/orthanc-defaults.json
        timeout: 30
        expected_output: |
          Orthanc has started
          Registering plugin.*housekeeper
          Registering plugin.*postgresql-storage
          Registering plugin.*postgresql-index
          Registering plugin.*ohif
          Registering plugin.*dicom-web
          Registering plugin.*gdcm
          Registering plugin.*orthanc-explorer-2
          Registering plugin.*python

update:
  enabled: true
  github:
    identifier: orthanc-server/orthanc-builder
    strip-prefix: v
