package:
  name: orthanc-explorer2
  version: 1.8.3
  epoch: 0
  description: Modern web interface for Orthanc DICOM server - Enhanced Explorer
  copyright:
    - license: AGPL-3.0-or-later
  dependencies:
    runtime:
      - boost-filesystem
      - boost-iostreams
      - boost-thread
      - jsoncpp
      - libuuid

environment:
  contents:
    packages:
      - boost-dev
      - build-base
      - busybox
      - e2fsprogs-dev
      - gtest-dev
      - jsoncpp-dev
      - libuuid
      - mercurial
      - nodejs
      - npm
      - patch
      - python3
      - util-linux-dev

pipeline:
  - uses: fetch
    with:
      uri: https://orthanc.uclouvain.be/downloads/sources/orthanc-explorer-2/OrthancExplorer2-${{package.version}}.tar.gz
      expected-sha256: ec7894700275e5150f7125e792f3cfea9e92496d36433bac109a68f60979ded5

  - name: Build web assets
    runs: |
      cd WebApplication
      echo "Installing Node.js dependencies..."
      npm install --no-audit --no-fund
      echo "Building web application..."
      npm run build
      echo "Web assets built successfully"
      ls -la dist/

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DALLOW_DOWNLOADS=ON \
        -DUSE_SYSTEM_ORTHANC_SDK=OFF \
        -DUSE_SYSTEM_JSONCPP=ON \
        -DUSE_SYSTEM_BOOST=ON \
        -DBUILD_TESTING=ON

  - uses: cmake/build

  - uses: cmake/install

  - runs: |
      # Install the Explorer2 plugin
      mkdir -p ${{targets.destdir}}/usr/lib/orthanc/plugins/
      if [ -f /usr/lib/libOrthancExplorer2.so ]; then
        cp /usr/lib/libOrthancExplorer2.so ${{targets.destdir}}/usr/lib/orthanc/plugins/
      fi

  - uses: strip

test:
  pipeline:
    - runs: |
        # Test that the plugin library exists and has correct format
        test -f /usr/lib/orthanc/plugins/libOrthancExplorer2.so
        ldd /usr/lib/orthanc/plugins/libOrthancExplorer2.so

update:
  enabled: true
  release-monitor:
    identifier: 18635
