---
package:
  name: orthanc
  version: "1.12.2"  # Adjust to match the Orthanc version discovered
  epoch: 0
  description: "Orthanc - a lightweight DICOM server for medical imaging"
  copyright:
    - license: "AGPL-3.0-or-later"

environment:
  contents:
    packages:
      - build-base
      - ninja
      - git
      - pkgconf
      - mercurial
      - zlib-dev
      - expat-dev
      - openssl-dev
      - curl-dev
      - sqlite-dev  # sometimes used if Orthanc is built with SQLite
      - boost-dev
      - busybox
      - patch
      - lua5.4-dev
      - doxygen
      - openssl-dev
      - libjpeg-turbo-dev
      - libpng-dev
      - tiff-dev
      - libxml2-dev
      - protobuf-dev
      - glibc-iconv
      - gnu-libiconv-dev
      - pugixml
      - gtest-dev
      - jsoncpp-dev
      - dcmtk
vars:
  lua-version: "5.4"

# Main build pipeline
pipeline:
  - runs: |
      hg clone https://orthanc.uclouvain.be/hg/orthanc -u Orthanc-${{package.version}}

  - uses: cmake/configure
    with:
      opts: |
        -DALLOW_DOWNLOADS=ON \
        -DUSE_BUNDLED_JSONCPP=On \
        -DUSE_SYSTEM_CIVETWEB=OFF \
        -DUSE_GOOGLE_TEST_DEBIAN_PACKAGE=OFF \
        -DDCMTK_LIBRARIES=dcmjpls \
        -DLUA_LIBRARIES=/usr/lib/lua${{vars.lua-version}}/liblua.so \
        -DCMAKE_BUILD_TYPE=Release \
        -DENABLE_PUGIXML=OFF \
        -S ./${{package.name}}/OrthancServer/
  - uses: cmake/build