package:
  name: orthanc-dicomweb
  version: 1.20
  epoch: 0
  description: DICOMweb plugin for Orthanc DICOM server - RESTful DICOM services
  copyright:
    - license: AGPL-3.0-or-later
  dependencies:
    runtime:
      - orthanc

environment:
  contents:
    packages:
      - boost-dev
      - build-base
      - busybox
      - e2fsprogs
      - gtest-dev
      - jsoncpp-dev
      - libuuid
      - patch
      - pugixml-dev
      - python3
      - util-linux-dev
      - zlib-dev

pipeline:
  - uses: fetch
    with:
      uri: https://orthanc.uclouvain.be/downloads/sources/orthanc-dicomweb/OrthancDicomWeb-${{package.version}}.tar.gz
      expected-sha256: 1e8adcaffc97b891bb7030987c47ccd4c4d952ac43217c9813164e963bd3a9ac

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DSTATIC_BUILD=ON \
        -DALLOW_DOWNLOADS=ON \
        -DUSE_SYSTEM_ORTHANC_SDK=OFF \
        -DUSE_SYSTEM_JSONCPP=ON \
        -DUSE_SYSTEM_PUGIXML=ON

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

test:
  environment:
    contents:
      packages:
        - python3
  pipeline:
    - runs: |
        # Test that the plugin library exists and has correct format
        test -f /usr/share/orthanc/plugins/libOrthancDicomWeb.so
    - name: Test plugin configuration format
      runs: |
        # Create a minimal test configuration to verify JSON structure
        cat > /tmp/test-config.json << 'EOF'
        {
          "Name" : "TestOrthanc",
          "Plugins" : [
            "/usr/share/orthanc/plugins/libOrthancDicomWeb.so"
          ],
          "DicomWeb" : {
            "Enable" : true,
            "Root" : "/dicom-web/",
            "EnableWado" : true,
            "WadoRoot" : "/wado"
          }
        }
        EOF

        # Validate JSON syntax
        python3 -m json.tool /tmp/test-config.json > /dev/null
        echo "Configuration JSON syntax is valid"

        # Check that plugin path in config matches installed location
        grep -q "/usr/share/orthanc/plugins/libOrthancDicomWeb.so" /tmp/test-config.json
        echo "Plugin path in configuration is correct"

update:
  enabled: true
  release-monitor:
    identifier: 378479
