---
package:
  name: pugixml
  version: "1.15"  # Adjust to match the Orthanc version discovered
  epoch: 0
  description: "Light-weight, simple and fast XML parser for C++ with XPath support"
  copyright:
    - license: "MIT"

environment:
  contents:
    packages:
      - build-base
      - busybox
vars:
  lua-version: "5.4"

# Main build pipeline
pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/zeux/pugixml.git
      tag: v${{package.version}}
      expected-commit: ee86beb30e4973f5feffe3ce63bfa4fbadf72f38
      recurse-submodules: true  

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install