package:
  name: pugixml
  version: "1.15"
  epoch: 0
  description: "Light-weight, simple and fast XML parser for C++ with XPath support"
  copyright:
    - license: "MIT"
  dependencies:
    runtime:
      - glibc
      - libgcc
      - libstdc++

environment:
  contents:
    packages:
      - build-base
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/zeux/pugixml.git
      tag: v${{package.version}}
      expected-commit: ee86beb30e4973f5feffe3ce63bfa4fbadf72f38
      recurse-submodules: true

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DBUILD_SHARED_LIBS=ON \
        -DBUILD_TESTS=ON \
        -DBUILD_PKGCONFIG=ON \
        -GNinja

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    description: Development files for pugixml
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - pugixml

  - name: ${{package.name}}-doc
    description: Documentation for pugixml
    pipeline:
      - uses: split/manpages
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/doc/pugixml
          if [ -f README.md ]; then
            cp README.md "${{targets.subpkgdir}}"/usr/share/doc/pugixml/
          fi
          if [ -d docs ]; then
            cp -r docs/* "${{targets.subpkgdir}}"/usr/share/doc/pugixml/ || true
          fi

test:
  pipeline:
    - runs: |
        # Test that shared library exists
        test -f /usr/lib/libpugixml.so

        # Test that headers are installed
        test -f /usr/include/pugixml.hpp
        test -f /usr/include/pugiconfig.hpp

        # Test that pkg-config file exists and works
        test -f /usr/lib/pkgconfig/pugixml.pc
        pkg-config --exists pugixml

        # Show version information
        pkg-config --modversion pugixml
    - uses: test/tw/ldd-check
