package:
  name: py3-normalizer
  version: "3.4.2"
  epoch: 0
  description: "Truly universal encoding detector in pure Python"
  copyright:
    - license: MIT

vars:
  pypi-package: normalizer

data:
  - name: py-versions
    items:
      3.10: "310"
      3.11: "311"
      3.12: "312"
      3.13: "313"

environment:
  contents:
    packages:
      - py3-supported-build-base-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jawah/charset_normalizer.git
      tag: ${{package.version}}
      expected-commit: 6422af1d50f1f46624deab585424e1ac4d08ba94

subpackages:
  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}
    description: python${{range.key}} version of ${{vars.pypi-package}}
    dependencies:
      provides:
        - py3-${{vars.pypi-package}}
    pipeline:
      - uses: py/pip-build-install
        with:
          python: python${{range.key}}
      - uses: strip
    test:
      environment:
        contents:
          packages:
            - python-${{range.key}}
      pipeline:
        - uses: python/import
          with:
            python: python${{range.key}}
            import: charset_${{vars.pypi-package}}
        - runs: |
            # Test the package
            cat <<EOF > test.py
            from charset_normalizer import from_bytes, from_path
            my_byte_str = 'Bonjour, je suis à la recherche d\'une aide sur les étoiles'.encode('cp1252')
            print(
              str(
                from_bytes(
                  my_byte_str
                ).best()
              )
            )
            EOF
            python test.py | grep -q "Bonjour, je suis ŕ la recherche d'une aide sur les étoiles"

  - range: py-versions
    name: py${{range.key}}-${{vars.pypi-package}}-bin
    description: Executable binaries for ${{vars.pypi-package}} installed for python${{range.key}}
    dependencies:
      runtime:
        - py${{range.key}}-${{vars.pypi-package}}
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr
          mv ${{targets.contextdir}}/../py${{range.key}}-${{vars.pypi-package}}/usr/bin ${{targets.contextdir}}/usr
    test:
      pipeline:
        - runs: |
            normalizer -h | grep "usage"
            normalizer --version | grep ${{package.version}}

  - name: py3-supported-${{vars.pypi-package}}
    description: meta package providing ${{vars.pypi-package}} for supported python versions.
    dependencies:
      runtime:
        - py3.10-${{vars.pypi-package}}
        - py3.11-${{vars.pypi-package}}
        - py3.12-${{vars.pypi-package}}
        - py3.13-${{vars.pypi-package}}

update:
  enabled: true
  manual: false
  github:
    identifier: jawah/charset_normalizer
