package:
  name: pypy-3.11
  description: PyPy is a very fast and compliant implementation of the Python language v 3.11
  epoch: 0
  version: 7.3.18
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - pypy3=3.10.999
      - python-3=3.10.999
  dependencies:
    runtime:
      - bzip2-dev
      - ncurses
      - zlib

environment:
  contents:
    packages:
      - build-base
      - busybox
      - bzip2-dev
      - expat-dev
      - gdbm-dev
      - libffi
      - libffi-pic-dev
      - linux-headers
      - ncurses-dev
      - openssl-dev
      - perl
      - pypy-bootstrap
      - readline-dev
      - rpcgen
      - rsync
      - sqlite-dev
      - tcl-dev
      - tk-dev
      - xz-dev
      - zlib-dev

var-transforms:
  - from: ${{package.name}}
    match: ^pypy-(\d+\.\d+).*
    replace: $1
    to: extracted-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pypy/pypy.git
      tag: release-pypy${{vars.extracted-version}}-v${{package.version}}
      expected-commit: b38de282ceade09de223a35c450387da97e4938b

  - uses: patch
    with:
      patches: 0001-refactor-update-type-definitions-and-improve-signal-.patch

  - working-directory: pypy/goal
    runs: |
      /usr/lib/pypy/bin/pypy-c ../../rpython/bin/rpython --opt=jit --shared targetpypystandalone

  - runs: |
      mkdir -p ${{targets.contextdir}}/usr/bin

      install -Dm755 pypy/goal/pypy${{vars.extracted-version}}-c "${{targets.contextdir}}"/usr/bin/pypy${{vars.extracted-version}}-c
      install -Dm755 pypy/goal/libpypy${{vars.extracted-version}}-c.so "${{targets.contextdir}}"/usr/bin/libpypy${{vars.extracted-version}}-c.so

      # # Install symlinks
      ln -s pypy${{vars.extracted-version}}-c  ${{targets.contextdir}}/usr/bin/pypy

      rsync -r --exclude='__pycache__' --exclude='test' --exclude='tests' lib-python/ "${{targets.contextdir}}"/usr/lib-python/
      rsync -r --exclude='__pycache__' --exclude='*.c' --exclude '*.o' lib_pypy/ "${{targets.contextdir}}"/usr/lib_pypy/
      rsync -r --include='*.h' -f 'hide,! */' include/ "${{targets.contextdir}}"/usr/include/

  - runs: |
      ${{targets.contextdir}}/usr/bin/pypy${{vars.extracted-version}}-c -m ensurepip --default-pip
      ${{targets.contextdir}}/usr/bin/pypy${{vars.extracted-version}}-c -m pip install --upgrade pip setuptools wheel
      sed -i '1s|^#!.*|#!/usr/bin/pypy|' ${{targets.contextdir}}/usr/bin/pip3

      # remove old pip and add symlink to new pip
      rm -f ${{targets.contextdir}}/usr/bin/pip
      ln -s pip3 ${{targets.contextdir}}/usr/bin/pip

  - uses: strip

subpackages:
  - name: ${{package.name}}-dev
    description: PyPy 3.11 development files
    dependencies:
      runtime:
        - ${{package.name}}
    pipeline:
      - runs: |
          mkdir -p "{{targets.contextdir}}"/usr/include
          mv "${{targets.destdir}}"/usr/include/pypy-3.11/pyconfig.h "${{targets.contextdir}}"/usr/include/

  - name: ${{package.name}}-compat
    description: PyPy 3.11 compatibility layer
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr/local/bin/
          mkdir -p ${{targets.contextdir}}/opt/pypy/bin
          ln -s /usr/bin/pypy${{vars.extracted-version}}-c ${{targets.contextdir}}/usr/local/bin/pypy3
          ln -s /usr/bin/pypy${{vars.extracted-version}}-c ${{targets.contextdir}}/opt/pypy/bin/pypy3
          ln -s /usr/bin/pip3 ${{targets.contextdir}}/opt/pypy/bin/pip
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}
      pipeline:
        - runs: stat /opt/pypy/bin/pypy3
        - runs: stat /opt/pypy/bin/pip
        - runs: |
            export PATH=$PATH:/opt/pypy/bin
            pypy3 --version

test:
  pipeline:
    - name: "check version"
      uses: test/daemon-check-output
      with:
        start: "pypy --version"
        timeout: 120
        expected_output: |
          PyPy ${{package.version}}
    - runs: pypy -c "import os, sys, math, random, datetime; print('Modules OK')"
    - name: "check pip installation"
      runs: pip --version
    - name: "install and check package with pip"
      runs: |
        pip install requests
        pypy -c "import requests; print(requests.__version__)"
    - runs: |
        cat <<EOF >test.py
        import time

        def test_pypy_jit():
            def expensive_loop():
                x = 0
                for i in range(10**6):
                    x += i % 3
                return x

            start = time.time()
            expensive_loop()
            end = time.time()
            print("Execution time:", end - start)

        test_pypy_jit()
        EOF
        pypy test.py

update:
  enabled: true
  github:
    identifier: pypy/pypy
    strip-prefix: release-pypy3.11-v
    use-tag: true
