package:
  name: pypy-3.11
  description: PyPy is a very fast and compliant implementation of the Python language v 3.11
  epoch: 0
  version: 7.3.18
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - bzip2-dev
      - ncurses
      - zlib

environment:
  contents:
    packages:
      - pypy-bootstrap
      - build-base
      - busybox
      - bzip2-dev
      - expat-dev
      - gdbm-dev
      - linux-headers
      - ncurses-dev
      - openssl-dev
      - perl
      - readline-dev
      - rpcgen
      - rsync
      - sqlite-dev
      - tk-dev
      - xz-dev
      - zlib-dev
      - libffi
      - libffi-pic-dev
      - tcl-dev

var-transforms:
  - from: ${{package.name}}
    match: ^pypy-(\d+\.\d+).*
    replace: $1
    to: extracted-version

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pypy/pypy.git
      tag: release-pypy${{vars.extracted-version}}-v${{package.version}}
      expected-commit: b38de282ceade09de223a35c450387da97e4938b

  - uses: patch
    with:
      patches: 0001-refactor-update-type-definitions-and-improve-signal-.patch

  - working-directory: pypy/goal
    runs: |
      /usr/lib/pypy/bin/pypy-c ../../rpython/bin/rpython --opt=jit --shared targetpypystandalone

  - runs: |
      mkdir -p ${{targets.contextdir}}/usr/bin/pypy-c
      mkdir -p ${{targets.contextdir}}/usr/lib/
      mkdir -p ${{targets.contextdir}}/usr/bin
      install -Dm755 pypy/goal/pypy${{vars.extracted-version}}-c "${{targets.contextdir}}"/usr/bin/pypy${{vars.extracted-version}}-c
      install -Dm755 pypy/goal/libpypy${{vars.extracted-version}}-c.so "${{targets.contextdir}}"/usr/bin/libpypy${{vars.extracted-version}}-c.so

      rsync -r --exclude='__pycache__' --exclude='test' --exclude='tests' lib-python/ "${{targets.contextdir}}"/usr/lib-python/
      rsync -r --exclude='__pycache__' --exclude='*.c' --exclude '*.o' lib_pypy/ "${{targets.contextdir}}"/usr/lib_pypy/
      rsync -r --include='*.h' -f 'hide,! */' include/ "${{targets.contextdir}}"/usr/include/

      # # Install symlinks
      ln -s pypy${{vars.extracted-version}}-c  ${{targets.contextdir}}/usr/bin/pypy

subpackages:
  - name: ${{package.name}}-compat
    description: PyPy 3.11 compatibility layer
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/usr/local/bin/
          mkdir -p ${{targets.contextdir}}/opt/pypy/bin
          ln -s /usr/bin/pypy${{vars.extracted-version}}-c ${{targets.contextdir}}/usr/local/bin/pypy3
          ln -s /usr/bin/pypy${{vars.extracted-version}}-c ${{targets.contextdir}}/opt/pypy/bin/pypy3
    test:
      pipeline:
        - runs: pypy3 --version
        - runs: pypy3 -c "import os, sys, math, random, datetime; print('Modules OK')"

test:
  pipeline:
    - runs: pypy --version
    - runs: pypy -c "import os, sys, math, random, datetime; print('Modules OK')"
    - runs: |
        cat <<EOF >test.py
        import time

        def test_pypy_jit():
            def expensive_loop():
                x = 0
                for i in range(10**6):
                    x += i % 3
                return x

            start = time.time()
            expensive_loop()
            end = time.time()
            print("Execution time:", end - start)

        test_pypy_jit()
        EOF
        pypy test.py

update:
  enabled: true
  github:
    identifier: pypy/pypy
    strip-prefix: release-pypy3.11-v
    use-tag: true
