package:
  name: pypy
  epoch: 0
  version: 7.3.18
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - bzip2-dev
      - expat-dev
      - gdbm-dev
      - libffi
      - libffi-dev
      - libstdc++
      - libstdc++
      - linux-headers
      - ncurses-dev
      - openssl-dev>3
      - perl
      - posix-libc-utils
      - readline-dev
      - rpcgen
      - rsync
      - sqlite-dev
      - subunit-dev
      - tk-dev
      - util-linux-misc
      - wget
      - xz-dev
      - zlib-dev

pipeline:
  - uses: git-checkout
    working-directory: python
    with:
      repository: https://github.com/python/cpython.git
      tag: v2.7.18
      expected-commit: 8d21aa21f2cbc6d50aab3f420bb23be1d081dac4

  - uses: autoconf/configure
    working-directory: python
    with:
      opts: |
        --enable-ipv6 \
        --enable-shared \
        --enable-unicode=ucs4 \
        --with-system-expat \
        --with-system-ffi \
        --with-system-zlib \
        --with-threads

  - uses: autoconf/make
    working-directory: python

  - uses: autoconf/make-install
    working-directory: python

  - uses: git-checkout
    working-directory: pycparser
    with:
      repository: https://github.com/eliben/pycparser.git
      ## v2.21 is the last version of pycparser with python2.7 compatibility. v2.22 expects python3
      tag: release_v2.21
      expected-commit: 3cf6bf5eb16f5eadd4a058e41596145c407a79ad

  - working-directory: pycparser
    runs: |
      export LD_LIBRARY_PATH=/home/build/melange-out/pypy/usr/lib:$LD_LIBRARY_PATH
      /home/build/melange-out/pypy/usr/bin/python setup.py install

  - uses: git-checkout
    with:
      repository: https://github.com/pypy/pypy.git
      tag: release-pypy3.11-v${{package.version}}
      expected-commit: b38de282ceade09de223a35c450387da97e4938b

  - uses: patch
    with:
      patches: pointer.patch signal.patch pyconfig.patch

  - runs: |
      cd pypy/goal
      export LD_LIBRARY_PATH=/home/build/melange-out/pypy/usr/lib:$LD_LIBRARY_PATH
      /home/build/melange-out/pypy/usr/bin/python ../../rpython/bin/rpython --opt=jit --shared targetpypystandalone
      PYTHONPATH=../.. ./pypy-c ../../lib_pypy/pypy_tools/build_cffi_imports.py

update:
  enabled: true
  github:
    identifier: pypy/pypy
    strip-prefix: v
    tag-filter-prefix: release-pypy3.11-v
