package:
  name: pypy
  epoch: 0
  version: 7.3.18
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - bzip2-dev
      - expat-dev
      - gdbm-dev
      - libffi
      - libffi-dev
      - linux-headers
      - ncurses-dev
      - openssl-dev>3
      - perl
      - posix-libc-utils
      - readline-dev
      - rpcgen
      - rsync
      - sqlite-dev
      - subunit-dev
      - tk-dev
      - util-linux-misc
      - wget
      - xz-dev
      - zlib-dev

pipeline:
  # - runs: |
  #     if [[ "$(uname -m)" == "x86_64" ]]; then
  #       wget -O pypy2.7-v7.3.18-linux64.tar.bz2 "https://downloads.python.org/pypy/pypy2.7-v7.3.18-linux64.tar.bz2"

  #       # Verify SHA512 checksum
  #       echo "2388f62dfc1817cf9e9d5e4b357178992988d7e0b958aa40fb7a8dcab9af89ccf1468a6598aabce1b1c04d8277b12f294f0819048713fee92c940e74785933e8  pypy2.7-v7.3.18-linux64.tar.bz2" | sha512sum -c -
  #       if [[ $? -ne 0 ]]; then
  #         echo "Checksum verification failed!"
  #         exit 1
  #       fi

  #       # Extract with the correct options
  #       tar -xjf pypy2.7-v7.3.18-linux64.tar.bz2 -C /tmp/
  #     fi

  # - runs: |
  #     if [[ "$(uname -m)" == "x86_64" ]]; then
  #       wget -O pypy2.7-v7.3.18-aarch64.tar.bz2 "https://downloads.python.org/pypy/pypy2.7-v7.3.18-aarch64.tar.bz2"
  #       echo "25012972e33fb713cac4771dce043f249c588514bb35827eccc2c5bd47fb921a4f7e1945abca69859279f9bb2110bfdb529f2c41f114a111d475e687d906b019 pypy2.7-v7.3.18-aarch64.tar.bz2" | sha512sum -c -
  #       if [[ $? -ne 0 ]]; then
  #         echo "Checksum verification failed!"
  #         exit 1
  #       fi
  #         # Extract with the correct options
  #       tar -xjf pypy2.7-v7.3.18-aarch64.tar.bz2 -C /tmp/
  #     fi

  - uses: git-checkout
    working-directory: python
    with:
      repository: https://github.com/python/cpython.git
      tag: v2.7.18
      expected-commit: 8d21aa21f2cbc6d50aab3f420bb23be1d081dac4

  - uses: autoconf/configure
    working-directory: python
    with:
      opts: |
        --enable-ipv6 \
        --enable-shared \
        --enable-unicode=ucs4 \
        --with-system-expat \
        --with-system-ffi \
        --with-system-zlib \
        --with-threads

  - uses: autoconf/make
    working-directory: python

  - uses: autoconf/make-install
    working-directory: python

  - runs: |
      export LD_LIBRARY_PATH=/home/build/melange-out/pypy/usr/lib:$LD_LIBRARY_PATH
      /home/build/melange-out/pypy/usr/bin/python -m ensurepip
      /home/build/melange-out/pypy/usr/bin/python -m pip install pycparser

  - uses: git-checkout
    with:
      repository: https://github.com/pypy/pypy.git
      tag: release-pypy3.11-v${{package.version}}
      expected-commit: b38de282ceade09de223a35c450387da97e4938b

  - uses: patch
    with:
      patches: pointer.patch signal.patch pyconfig.patch

  - runs: |
      cd pypy/goal
      export LD_LIBRARY_PATH=/home/build/melange-out/pypy/usr/lib:$LD_LIBRARY_PATH
      /home/build/melange-out/pypy/usr/bin/python ../../rpython/bin/rpython --opt=jit --shared targetpypystandalone
      PYTHONPATH=../.. ./pypy-c ../../lib_pypy/pypy_tools/build_cffi_imports.py
