package:
  name: redpanda
  version: "25.1.3"
  description: "Redpanda is a streaming platform based on Apache Kafka API"
  resources:
    cpu: 16
    memory: 16Gi
  copyright:
    - license: "Apache-2.0"
  dependencies:
    runtime:
      - e2fsprogs
      - glibc
      - krb5-libs
      - libaio
      - numactl
      - openssl

environment:
  contents:
    packages:
      - abseil-cpp-dev
      - autoconf
      - automake
      - bash
      - bazelisk-default
      - binutils
      - bison
      - boost-dev
      - build-base
      - busybox
      - c-ares-dev
      - ca-certificates-bundle
      - cargo-auditable
      - cargo-c
      - ccache
      - clang
      - cmake
      - coreutils
      - cryptopp
      - doxygen
      - fmt-dev
      - git
      - glibc-locale-en
      - gnutls-dev
      - go
      - hwloc-dev
      - isl-dev
      - krb5-dev
      - libaio-dev
      - libcom_err
      - libsctp-dev
      - libtool
      - liburing-dev
      - libuuid
      - libxml2-dev
      - llvm-lld-18
      - lz4-dev
      - numactl-dev
      - openjdk-21-default-jdk
      - openssl-dev
      - patch
      - pcre2-dev
      - pkgconf-dev
      - protobuf-dev
      - protobuf-dev
      - py3.12-absl-py
      - py3.12-jinja2
      - py3.12-jsonschema
      - py3.12-pip
      - py3.12-requests
      - py3.12-six
      - python-3.12
      - ragel
      - re2-dev
      - rust
      - s3cmd
      - samurai
      - snappy-dev
      - util-linux-dev
      - valgrind-dev
      - xfs-scrub
      - xfsprogs-dev
      - xxhash-dev
      - yaml-cpp-dev
      - yamllint
      - zlib-dev
      - zstd-dev

pipeline:
  - uses: git-checkout
    with:
      repository: "https://github.com/redpanda-data/redpanda.git"
      expected-commit: "d88a59cf33e5d0442c79a075a05b4f82867d7d75"
      tag: "v${{package.version}}"
      destination: redpanda

  - working-directory: redpanda
    runs: |
      cd src/go/rpk
      go mod tidy

  - working-directory: redpanda
    runs: |
      bazel build --verbose_failures --show_loading_progress --config=release //...
      mkdir -p ${{targets.destdir}}/usr/bin/
      mkdir -p ${{targets.destdir}}/usr/lib/redpanda
      mv bazel-bin/src/v/redpanda/redpanda ${{targets.destdir}}/usr/bin/
      # This library is compiled by krb5 and not provided by any package.
      cp bazel-out/k8-opt/bin/external/_main\~non_module_dependencies\~krb5/krb5/lib/libcom_err.so.3 ../melange-out/redpanda/usr/lib/redpanda/
      mv bazel-bin/src/go/rpk/cmd/rpk/rpk_/rpk ${{targets.destdir}}/usr/bin/

subpackages:
  - name: ${{package.name}}-dev
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/pkgconf
        - uses: test/tw/ldd-check

test:
  pipeline:
    - uses: test/tw/ldd-check
    - runs: |
        redpanda --version
        rpk --version

update:
  enabled: true
  github:
    identifier: "redpanda-data/redpanda"
    strip-prefix: "v"
