package:
  name: redpanda-25.1
  version: "25.1.4"
  description: "Redpanda is a streaming platform based on Apache Kafka API"
  resources:
    cpu: 63
    memory: 140Gi
  copyright:
    - license: "Apache-2.0"
  dependencies:
    provides:
      - redpanda=${{package.full-version}}
    runtime:
      - bash
      - coreutils
      - e2fsprogs
      - glibc
      - krb5-libs
      - libaio
      - numactl
      - openssl

environment:
  contents:
    packages:
      - abseil-cpp-dev
      - autoconf
      - automake
      - bash
      - bazelisk-default
      - binutils
      - bison
      - boost-dev
      - build-base
      - busybox
      - c-ares-dev
      - ca-certificates-bundle
      - cargo-auditable
      - cargo-c
      - ccache
      - clang
      - cmake
      - coreutils
      - crane
      - doxygen
      - fmt-dev
      - git
      - glibc-locale-en
      - gnutls-dev
      - go
      - hwloc-dev
      - isl-dev
      - krb5-dev
      - libaio-dev
      - libcom_err
      - libsctp-dev
      - libtool
      - liburing-dev
      - libuuid
      - libxml2-dev
      - llvm-lld-18
      - lz4-dev
      - numactl-dev
      - openssl-dev
      - patch
      - pcre2-dev
      - pkgconf-dev
      - ragel
      - re2-dev
      - rust
      - s3cmd
      - samurai
      - snappy-dev
      - util-linux-dev
      - valgrind-dev
      - xfs-scrub
      - xfsprogs-dev
      - xxhash-dev
      - yaml-cpp-dev
      - yamllint
      - zlib
      - zstd
  environment:
    REDPANDA_VERSION: ${{package.version}}
    STABLE_GIT_VERSION: ${{package.version}}

pipeline:
  - uses: git-checkout
    with:
      repository: "https://github.com/redpanda-data/redpanda.git"
      expected-commit: "6cd1d4ef6b8424ee4fd219df94a90abe839a36bc"
      tag: "v${{package.version}}"
      destination: redpanda

  - working-directory: redpanda
    uses: patch
    with:
      patches: ../0001-build-update-krb5-configuration-to-include-system-er.patch

  - working-directory: redpanda
    runs: |
      mkdir -p ${{targets.destdir}}/usr/bin/
      bazel build --verbose_failures --stamp --action_env=STABLE_GIT_VERSION --action_env=REDPANDA_VERSION=${{package.version}} --show_loading_progress --config=release --strategy=sandboxed --jobs=16 --local_resources=memory=28000 --local_resources=cpu=22 //...
      mv bazel-bin/src/v/redpanda/redpanda ${{targets.destdir}}/usr/bin/
      mv bazel-bin/src/go/rpk/cmd/rpk/rpk_/rpk ${{targets.destdir}}/usr/bin/
      # Copy redpanda config file to default location /etc/redpanda
      mkdir -p ${{targets.destdir}}/etc/redpanda
      cp conf/redpanda.yaml ${{targets.destdir}}/etc/redpanda/redpanda.yaml

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    pipeline:
      - runs: |
          expected_sha=c61cfb940c3a534e79c5ae94c56da37ce11a8451bd74d132c7a96f579d1fe2bbf7d02fa555fe8b6c4dba0ee3fe5a873671bbbd9c1b756cf4e5031daac7f548c0
          tag=v${{package.version}}
          digest="$(crane digest redpandadata/redpanda:${tag})"
          crane export redpandadata/redpanda@${digest} - | tar -xvf - entrypoint.sh
          actual_sha="$(sha512sum entrypoint.sh | awk '{print $1}')"
          if [ "${actual_sha}" != "${expected_sha}" ]; then
            echo "FATAL: entrypoint.sh checksum mismatch!" >&2
            exit 1
          fi
          mkdir -p ${{targets.subpkgdir}}/
          mv entrypoint.sh ${{targets.subpkgdir}}/

  - name: ${{package.name}}-dev
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  environment:
    contents:
      packages:
        - ${{package.name}}-compat
  pipeline:
    - uses: test/tw/ldd-check
    - name: "Verify binary versions"
      runs: |
        redpanda --version > /dev/null 2>&1
        rpk --version > /dev/null 2>&1
    - name: "Test rpk commands"
      runs: |
        # A full blown redpanda cluster requires resources that the CI cluster cannot provide
        rpk redpanda start --mode dev-container --smp 1 --memory 1G --node-id 0 > /tmp/redpanda.log 2>&1 &
        sleep 5
        rpk cluster health | grep -iE '^Healthy:[[:space:]]+true$'
        rpk topic create tutorial 2>&1
        rpk topic list 2>&1| grep tutorial
    - name: "test entrypoint usage"
      runs: |
        /entrypoint.sh --help > /dev/null 2>&1

update:
  ignore-regex-patterns:
    - '-rc\d+$'
  enabled: true
  github:
    identifier: "redpanda-data/redpanda"
    strip-prefix: "v"
    use-tag: true
