package:
  name: redpanda
  version: "25.1.3"
  description: "Redpanda is a streaming platform based on Apache Kafka API"
  copyright:
    - license: "Apache-2.0"
  dependencies:
    runtime:
      - glibc
      - krb5-libs
      - libaio
      - libgcc
      - openssl

environment:
  contents:
    packages:
      - abseil-cpp-dev
      - autoconf
      - automake
      - bash
      - bazelisk-default
      - binutils
      - bison
      - boost-dev
      - brotli-dev
      - build-base
      - busybox
      - c-ares-dev
      - ca-certificates-bundle
      - cargo-auditable
      - cargo-c
      - ccache
      - clang-18-dev
      - cmake
      - coreutils
      - crc32c-dev
      - cryptopp
      - doxygen
      - fmt # Add the fmt runtime library
      - fmt-dev
      - git
      - glibc-locale-en
      - gnutls-dev
      - go
      - gtest-dev
      - hwloc-dev
      - isl-dev
      - krb5-dev
      - libaio-dev
      - libcom_err
      - libprotobuf
      - libprotoc
      - libsctp-dev
      - libtool
      - liburing-dev
      - libuuid
      - libxml2-dev
      - llvm-lld-18
      - lz4-dev
      - numactl-dev
      - openjdk-21-default-jdk
      - openssl
      - openssl-dev
      - patch
      - pcre2-dev
      - pkgconf-dev
      - procps-dev
      - protobuf-dev
      - protoc
      - py3.13-absl-py
      - py3.13-jinja2
      - py3.13-jsonschema
      - py3.13-pip
      - py3.13-requests
      - py3.13-six
      - python-3.13
      - ragel
      - rapidjson-dev
      - re2-dev
      - rust
      - s3cmd
      - samurai
      - seastar
      - snappy-dev
      - util-linux-dev
      - valgrind-dev
      - xfs-scrub
      - xfsprogs-dev
      - xxhash-dev
      - yaml-cpp-dev
      - yamllint
      - zlib-dev
      - zstd-dev

pipeline:
  - uses: git-checkout
    with:
      repository: "https://github.com/redpanda-data/redpanda.git"
      expected-commit: "d88a59cf33e5d0442c79a075a05b4f82867d7d75"
      tag: "v${{package.version}}"

  - uses: cmake/configure
    with:
      opts: |
        -DREDPANDA_ENABLE_TESTS=OFF \
        -DCMAKE_BUILD_TYPE=Release \
        -DLZ4_LIBRARY=/usr/lib/liblz4.so \
        -DCMAKE_PREFIX_PATH=/usr/lib/cmake/protobuf \
        -DProtobuf_INCLUDE_DIR=/usr/include \
        -DProtobuf_LIBRARY=/usr/lib/libprotobuf.so \
        -DLZ4_INCLUDE_DIR=/usr/include \

update:
  enabled: true
  github:
    identifier: "redpanda-data/redpanda"
    strip-prefix: "v"
