package:
  name: redpanda
  version: "25.1.4"
  description: "Redpanda is a streaming platform based on Apache Kafka API"
  resources:
    cpu: 63
    memory: 140Gi
  copyright:
    - license: "Apache-2.0"
  dependencies:
    runtime:
      - bash
      - e2fsprogs
      - glibc
      - krb5-libs
      - libaio
      - numactl
      - openssl

vars:
  py-version: 3.13
  java-version: 21

environment:
  contents:
    packages:
      - abseil-cpp-dev
      - autoconf
      - automake
      - bash
      - bazelisk-default
      - binutils
      - bison
      - boost-dev
      - build-base
      - busybox
      - c-ares-dev
      - ca-certificates-bundle
      - cargo-auditable
      - cargo-c
      - ccache
      - clang
      - cmake
      - coreutils
      - crane
      - doxygen
      - fmt-dev
      - git
      - glibc-locale-en
      - gnutls-dev
      - go
      - hwloc-dev
      - isl-dev
      - krb5-dev
      - libaio-dev
      - libcom_err
      - libsctp-dev
      - libtool
      - liburing-dev
      - libuuid
      - libxml2-dev
      - llvm-lld-18
      - lz4-dev
      - numactl-dev
      - openjdk-${{vars.java-version}}-default-jdk
      - openssl-dev
      - patch
      - pcre2-dev
      - pkgconf-dev
      - py${{vars.py-version}}-absl-py
      - py${{vars.py-version}}-jinja2
      - py${{vars.py-version}}-jsonschema
      - py${{vars.py-version}}-pip
      - py${{vars.py-version}}-requests
      - py${{vars.py-version}}-six
      - python-${{vars.py-version}}
      - ragel
      - re2-dev
      - rust
      - s3cmd
      - samurai
      - snappy-dev
      - util-linux-dev
      - valgrind-dev
      - xfs-scrub
      - xfsprogs-dev
      - xxhash-dev
      - yaml-cpp-dev
      - yamllint
      - zlib-dev
      - zstd-dev
  environment:
    RELEASE_VERSION: ${{package.version}}

pipeline:
  - uses: git-checkout
    with:
      repository: "https://github.com/redpanda-data/redpanda.git"
      expected-commit: "6cd1d4ef6b8424ee4fd219df94a90abe839a36bc"
      tag: "v${{package.version}}"
      destination: redpanda

  - working-directory: redpanda
    uses: patch
    with:
      patches: ../0001-build-update-krb5-configuration-to-include-system-er.patch

  - working-directory: redpanda
    runs: |
      mkdir -p ${{targets.destdir}}/usr/bin/
      mkdir -p ${{targets.destdir}}/usr/lib/redpanda
      bazel build --verbose_failures --action_env=RELEASE_VERSION=${{package.version}} --show_loading_progress --config=release --strategy=sandboxed --jobs=16 --local_ram_resources=28000 --local_cpu_resources=22 //...
      mv bazel-bin/src/v/redpanda/redpanda ${{targets.destdir}}/usr/bin/
      mv bazel-bin/src/go/rpk/cmd/rpk/rpk_/rpk ${{targets.destdir}}/usr/bin/
      # Copy redpanda config file to default location /etc/redpanda
      mkdir -p ${{targets.destdir}}/etc/redpanda
      cp conf/redpanda.yaml ${{targets.destdir}}/etc/redpanda/redpanda.yaml

  - uses: strip

subpackages:
  - name: ${{package.name}}-compat
    pipeline:
      - runs: |
          tag=v${{package.version}}
          crane export redpandadata/redpanda:${tag} - | tar -xvf - entrypoint.sh
          mv entrypoint.sh ${{targets.subpkgdir}}/

  - name: ${{package.name}}-dev
    pipeline:
      - uses: split/dev
    test:
      pipeline:
        - uses: test/tw/ldd-check

test:
  environment:
    contents:
      packages:
        - ${{package.name}}-compat
  pipeline:
    - uses: test/tw/ldd-check
    - name: "Verify binary versions"
      runs: |
        redpanda --version
        rpk --version
    - name: "Test rpk commands"
      runs: |
        rpk start --overprovisioned &
        sleep 5
        rpk cluster health | grep -iE '^Healthy:[[:space:]]+true$'
        rpk topic create tutorial
        rpk topic list | grep tutorial
    - name: "Test rpk cluster commands"
      runs: |
        rpk cluster --help
        rpk cluster info --help
    - name: "test entrypoint usage"
      runs: |
        /entrypoint.sh --help

update:
  enabled: true
  github:
    identifier: "redpanda-data/redpanda"
    strip-prefix: "v"
    use-tag: true
