package:
  name: seastar
  epoch: 0
  version: "22.11.0"
  description: "Seastar is a high-performance, open-source framework for building C++ applications"
  copyright:
    - license: "Apache-2.0"
  dependencies:
    runtime:
      - boost
      - c-ares
      - fmt-dev
      - protobuf-dev
      - gnutls
      - hwloc
      - libsctp
      - liburing
      - lz4
      - openssl
      - yaml-cpp

environment:
  contents:
    packages:
      - bison
      - boost-dev
      - build-base
      - busybox
      - c-ares-dev
      - cryptopp
      - doxygen
      - fmt-dev
      - gnutls-dev
      - hwloc-dev
      - libsctp-dev
      - liburing-dev
      - libuuid
      - lz4-dev
      - numactl-dev
      - protobuf-dev
      - python-3.11
      - ragel
      - util-linux-dev
      - valgrind-dev
      - xfs-scrub
      - xfsprogs-dev
      - yaml-cpp-dev

pipeline:
  - uses: git-checkout
    with:
      repository: "https://github.com/scylladb/seastar.git"
      branch: "master"
      # tag: seastar-${{package.version}}
      # expected-commit: 10b7d604d1f5037a733879d8d171d4405faebbe9: master

  # Configure step

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DSeastar_CXX_FLAGS="-Wno-error=deprecated-declarations" \
        -DCMAKE_CXX_STANDARD=20 \
        -DCMAKE_CXX_FLAGS="-Wno-error" \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DSeastar_TESTING=OFF \
        -DWITH_SSL=system \
        -DWITH_VALGRIND=OFF \
        -DWITH_ZLIB=system \
        -DWITH_BOOST=system \
        -DWITH_SYSTEM_FMT=ON \
        -G Ninja

  # Build step
  - uses: cmake/build

  # Install step
  - uses: cmake/install

  - uses: strip
