package:
  name: sops
  version: "3.10.0"
  epoch: 0
  description: Simple and flexible tool for managing secrets
  copyright:
    - license: MPL-2.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/getsops/sops
      tag: v${{package.version}}
      expected-commit: 4ed7060298fbcd00cafa359121ca62091b85bb6f

  - uses: go/build
    with:
      modroot: .
      tidy: true
      packages: ./cmd/sops
      output: sops

update:
  enabled: true
  github:
    identifier: getsops/sops
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - gpg
        - gpg-agent
  pipeline:
    - uses: git-checkout
      with:
        repository: https://github.com/getsops/sops
        tag: v${{package.version}}
        expected-commit: 4ed7060298fbcd00cafa359121ca62091b85bb6f
    - name: version check
      runs: |
        sops --version
        sops --help
    - name: decrypt
      runs: |
        gpg-agent --daemon
        gpg --import pgp/sops_functional_tests_key.asc

        cd examples/all_in_one
        sops decrypt config/secret.enc.json
