package:
  name: spilo-17
  version: "4.0"
  epoch: 0
  description: "Spilo - a PostgreSQL container image with streaming replication and failover"
  copyright:
    - license: "Apache-2.0"
  options:
    no-depends: true
  dependencies:
    runtime:
      - dumb-init
      - etcd
      - glibc
      - openssl
      - patroni
      - postgresql
      - py3-psutil
      - py3-pyyaml
      - py3-requests
      - py3-six
      - py3.13-pystache
      - runit

environment:
  contents:
    packages:
      - brotli-dev
      - build-base
      - busybox
      - c-ares-dev
      - ca-certificates-bundle
      - etcd
      - gdal
      - libarchive-tools # bsdtar
      - libcap-utils
      - openssl-dev
      - patroni
      - perl
      - postgis
      - postgresql-dev
      - py3-pystache
      - wal-g-pg
  environment:
    RW_DIR: /run
    PGHOME: /home/postgres

vars:
  python-version: "3.11"

pipeline:
  - uses: git-checkout
    with:
      repository: "https://github.com/zalando/spilo.git"
      expected-commit: "4b3d1c6fc66170d8d6cf6a21218146e74ae014d0"
      tag: "${{package.version}}-p2"

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      mkdir -p ${{targets.destdir}}/etc/service
      mkdir -p ${{targets.destdir}}/scripts
      install -m755 postgres-appliance/launch.sh ${{targets.contextdir}}/usr/bin/
      cp -r postgres-appliance/scripts/* postgres-appliance/bootstrap/* postgres-appliance/major_upgrade/* ${{targets.destdir}}/scripts/
      cp postgres-appliance/motd ${{targets.destdir}}/etc/motd
      cp -r postgres-appliance/runit ${{targets.destdir}}/etc/service
      ln -snf "$RW_DIR/service" ${{targets.contextdir}}/etc/service

subpackages:
  - name: ${{package.name}}-compat
    description: "compat package with bitnami/spilo image"
    dependencies:
      runtime:
        - bash
        - ca-certificates-bundle
    pipeline:
      - runs: |
          mkdir -p ${{targets.contextdir}}/run/
          mkdir -p ${{targets.contextdir}}/.config/patroni
          mkdir -p ${{targets.contextdir}}/$PGHOME
          ln -s /usr/bin/launch.sh ${{targets.contextdir}}/
          ln -s "$RW_DIR/postgres.yml" "${{targets.contextdir}}/$PGHOME/postgres.yml"
          ln -s "$RW_DIR/etc" "${{targets.contextdir}}/$PGHOME/etc"
          ln -s "$PGHOME/postgres.yml" "${{targets.contextdir}}/.config/patroni/patronictl.yaml"
          mv postgres-appliance/cron_unprivileged.c ${{targets.contextdir}}/

test:
  environment:
    contents:
      packages:
        - busybox
        - ca-certificates-bundle
        - libarchive-tools # bsdtar
        - spilo-17-compat
        - python-3.13
        - sudo-rs
    accounts:
      groups:
        - groupname: postgres
          gid: 100
      users:
        - username: postgres
          gid: 100
          uid: 100
      run-as: 0
    environment:
      SPILO_PROVIDER: "local"
      DEBUG: "1"
      PGVERSION: "17"
      RW_DIR: /run
      SPILO_CONFIGURATION: |
        postgresql:
          bin_dir: /usr/bin
      PGLOG: /home/postgres/pgdata/pgroot/pg_log
      PGDATA: /home/postgres/pgdata/pgroot/data
      PGROOT: /home/postgres/pgdata/pgroot
      WAL_SWIFT_BUCKET: False
      PATRONIVERSION: "4.0.5"
  pipeline:
    - name: Run and test ${{package.name}}
      runs: |
        echo "127.0.0.1 $(hostname)" >> /etc/hosts
        mkdir -p "$RW_DIR"/{tmp,certs}
        mkdir -p "$PGDATA"
        chown postgres:postgres "/launch.sh"
        chown postgres:postgres /usr/bin/launch.sh

        sudo -u postgres launch.sh init

update:
  enabled: true
  manual: false
  github:
    identifier: "zalando/spilo"
    use-tag: true
